title: ModForge-Cli
description: "A modern CLI for building and managing Minecraft modpacks"
url: "https://frank1o3.github.io"
baseurl: "/ModForge-Cli"

remote_theme: just-the-docs/just-the-docs

color_scheme: dark

logo: "/assets/logo.png"
favicon_ico: "/assets/favicon.ico"

aux_links:
  "GitHub Repository": "https://github.com/Frank1o3/ModForge-Cli"

nav_enabled: true
search_enabled: true
heading_anchors: true

footer_content: "ModForge-Cli © 2026 Frank1o3 · MIT Licensed"